# Generated by Django 3.0.1 on 2021-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
