# Generated by Django 3.0.1 on 2021-06-21 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='review',
            field=models.IntegerField(default=[0], validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
