# Generated by Django 3.0.1 on 2021-06-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210621_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='review',
            field=models.IntegerField(default=[0]),
        ),
    ]
